cmake_minimum_required(VERSION 3.27)
project(Leetcode2_0)

set(CMAKE_CXX_STANDARD 17)

add_executable(Leetcode2_0 main.cpp)

add_executable(ClimbingStairs "1-D Dp/ClimbingStairs.cpp")
add_executable(MinCostClimbingStairs "1-D Dp/MinCostClimbingStairs.cpp")
add_executable(houseRobber "1-D Dp/houseRobber.cpp")
add_executable(HouseRobber-II "1-D Dp/HouseRobber-II.cpp")
add_executable(LongestPalindromicSubstring "1-D Dp/LongestPalindromicSubstring.cpp")